# Generated by Django 5.0.3 on 2025-05-29 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRIMERA', 'Primera Parte'), ('SEGUNDA', 'Segunda Parte')], max_length=10)),
                ('instrucciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('pagina', models.PositiveSmallIntegerField()),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.partetest')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1)),
                ('texto', models.CharField(max_length=300)),
                ('columna', models.CharField(max_length=1)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.preguntavalores')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('teorico', models.FloatField(default=0)),
                ('economico', models.FloatField(default=0)),
                ('estetico', models.FloatField(default=0)),
                ('social', models.FloatField(default=0)),
                ('politico', models.FloatField(default=0)),
                ('religioso', models.FloatField(default=0)),
                ('teorico_percentil', models.FloatField(blank=True, null=True)),
                ('economico_percentil', models.FloatField(blank=True, null=True)),
                ('estetico_percentil', models.FloatField(blank=True, null=True)),
                ('social_percentil', models.FloatField(blank=True, null=True)),
                ('politico_percentil', models.FloatField(blank=True, null=True)),
                ('religioso_percentil', models.FloatField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testvalores')),
            ],
        ),
        migrations.AddField(
            model_name='partetest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testvalores'),
        ),
    ]
