# Generated by Django 5.0.3 on 2025-06-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_resultadovalores_clasificaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadovalores',
            name='clasificaciones',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='resultadovalores',
            name='descripcion_dominante',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resultadovalores',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resultadovalores',
            name='meta_dominante',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resultadovalores',
            name='rangos_valores',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='resultadovalores',
            name='valor_dominante',
            field=models.CharField(max_length=50),
        ),
    ]
