# Generated by Django 5.0.3 on 2025-06-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_resultadovalores_clasificaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadovalores',
            name='clasificaciones',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadovalores',
            name='descripcion_dominante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadovalores',
            name='meta_dominante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resultadovalores',
            name='rangos_valores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadovalores',
            name='valor_dominante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
