# Generated by Django 5.0.3 on 2025-06-03 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_resultadovalores_clasificaciones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDomino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Test de Dominó D-48', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tiempo_limite', models.PositiveIntegerField(default=25, help_text='Tiempo en minutos')),
                ('instrucciones', models.TextField(blank=True)),
                ('tipo_disposicion', models.CharField(choices=[('MATRIZ', 'Matriz rectangular'), ('ESPIRAL', 'Disposición en espiral'), ('FLOR', 'Disposición floral')], default='MATRIZ', help_text='Tipo de disposición para los problemas', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDomino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('respuestas', models.JSONField()),
                ('puntuacion', models.PositiveIntegerField(default=0)),
                ('percentil', models.FloatField(blank=True, null=True)),
                ('tiempo_utilizado', models.PositiveIntegerField(default=0, help_text='Tiempo utilizado en segundos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_domino', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testdomino')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaDomino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('MATRIZ', 'Matriz rectangular'), ('ESPIRAL', 'Disposición en espiral'), ('FLOR', 'Disposición floral')], default='MATRIZ', help_text='Tipo de disposición del problema', max_length=10)),
                ('matriz_filas', models.PositiveIntegerField(blank=True, default=2, help_text='Número de filas (solo para tipo matriz)', null=True)),
                ('matriz_columnas', models.PositiveIntegerField(blank=True, default=3, help_text='Número de columnas (solo para tipo matriz)', null=True)),
                ('fichas', models.JSONField()),
                ('respuesta', models.JSONField()),
                ('configuracion_extra', models.JSONField(blank=True, help_text='Configuración adicional para disposiciones especiales', null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='tests.testdomino')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('test', 'numero')},
            },
        ),
    ]
